-- Create table for project requests
CREATE TABLE IF NOT EXISTS public.x_projects_requests
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL,
    priority text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Medium',
    estimated_budget text COLLATE pg_catalog."default",
    estimated_timeline text COLLATE pg_catalog."default",
    technical_requirements text COLLATE pg_catalog."default",
    contact_email text COLLATE pg_catalog."default",
    contact_telegram text COLLATE pg_catalog."default",
    submitter_name text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Open',
    votes integer NOT NULL DEFAULT 0,
    vote_ips text[] DEFAULT '{}',
    interested_developers text[] DEFAULT '{}',
    tags text[] DEFAULT '{}',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    published_at timestamp with time zone DEFAULT now(),
    CONSTRAINT x_projects_requests_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.x_projects_requests
    OWNER to postgres;

ALTER TABLE IF EXISTS public.x_projects_requests
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.x_projects_requests TO anon;

GRANT ALL ON TABLE public.x_projects_requests TO authenticated;

GRANT ALL ON TABLE public.x_projects_requests TO postgres;

GRANT ALL ON TABLE public.x_projects_requests TO service_role;

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_x_projects_requests_status ON public.x_projects_requests(status);
CREATE INDEX IF NOT EXISTS idx_x_projects_requests_category ON public.x_projects_requests(category);
CREATE INDEX IF NOT EXISTS idx_x_projects_requests_created_at ON public.x_projects_requests(created_at); 